SP-6318 prometheus refactor
stackpulse/steps pull request #102
Opened 2021-05-27 09:32 UTC by nshem

2021-05-27 12:45 UTC, oriser reviewed
Looks good! See comments and:
* Change to go 1.16 both in Docker base image and in go.mod
* Common test function should be under `testdata` folder (go compiler ignores this folder and won't compile it into the final binary, we will just accessible to it during tests"

2021-05-27 12:45 UTC, oriser commented on steps/prometheus/query/range/range_integration_test.go
> +			WantOutput:   matcher.All(matcher.TextContains("go_gc_duration_seconds"), matcher.StepStatus(codes.OK, "", "")),
Do you have some metrics you can check here?

2021-05-27 12:45 UTC, oriser commented on steps/prometheus/query/raw/raw_integration_test.go
> +			WantOutput:   matcher.All(matcher.TextContains("go_gc_duration_seconds"), matcher.StepStatus(codes.OK, "", "")),
Do you have some metrics you can check here?

2021-05-30 06:22 UTC, hagaishapira requested changes

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/range/range.go
> +		return status.FromError(codes.InvalidArgument, "parsing start time", err)
```suggestion
		return status.FromError(codes.InvalidArgument, "invalid start time", err)
```

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/range/range.go
> +			return status.FromError(codes.InvalidArgument, "parsing end time", err)
```suggestion
			return status.FromError(codes.InvalidArgument, "invalid end time", err)
```

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/range/range.go
> +	stepOutput := make(step.Output)
why do you need to do a make and not have a literal assignment ?

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/raw/raw.go
> +			return status.FromError(codes.InvalidArgument, "parsing time", err)
```suggestion
			return status.FromError(codes.InvalidArgument, "invalid time argument", err)
```

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/raw/raw.go
> +		return nil, status.FromError(codes.Internal, "query time", err)
This error message is not friendly enough. Does api.Query return different kinds of errors? can we map those to more friendly messages?

2021-05-30 06:22 UTC, hagaishapira commented on steps/prometheus/query/range/range.go
> +		return nil, status.FromError(codes.Internal, "query range", err)
Here as well, the message here is not friendly to a user. We should map query errors to friendly messages which the user can act upon.

2021-05-30 08:11 UTC, nshem commented on steps/prometheus/query/range/range.go
> +	}
done it cause im using isRelativeTimeArgs in another place + readability

2021-05-30 10:13 UTC, nshem commented on steps/prometheus/query/range/manifest.yaml
> +  - name: api_object
its not. armis are using it but a version that is in a branch (us-docker.pkg.dev/stackpulse/public/prometheus/query/raw:SP-2345)

2021-05-30 13:34 UTC, hagaishapira reviewed
See just the error behaviour explicitness

2021-05-30 13:34 UTC, hagaishapira commented on steps/prometheus/query/range/range.go
> +		return nil, status.FromError(base.MapApiErrorCode(err), "query range", err)
So other than mapping the code which is great we want to map the message and even add the error object in the verbose, just like we do in okta steps for example.
![image](https://user-images.githubusercontent.com/29172759/120106106-704e4480-c164-11eb-969e-78b7389604b8.png)

2021-05-30 13:34 UTC, hagaishapira commented on steps/prometheus/query/raw/raw.go
> +		return nil, status.FromError(base.MapApiErrorCode(err), "query time", err)
So other than mapping the code which is great we want to map the message and even add the error object in the verbose, just like we do in okta steps for example.
![image](https://user-images.githubusercontent.com/29172759/120106106-704e4480-c164-11eb-969e-78b7389604b8.png)

2021-05-30 14:22 UTC, hagaishapira approved these changes
Merge after type fix

2021-05-30 14:22 UTC, hagaishapira commented on steps/prometheus/base/prometheus.go
> +		return nil, status.FromError(codes.Unavailable, "failed creatung prometheus client", err)
```suggestion
		return nil, status.FromError(codes.Unavailable, "failed creating prometheus client", err)
```

2021-05-30 15:00 UTC, oriser approved these changes
Nice one small comment

2021-05-30 21:19 UTC, merged