SP-6321 opsgenie refactor
stackpulse/steps pull request #104
Opened 2021-05-30 16:16 UTC by nshem

2021-05-31 06:03 UTC, hagaishapira commented
@nshem is this PR ready?

2021-05-31 11:07 UTC, hagaishapira commented
@nshem Is this review ready ?

2021-05-31 12:00 UTC, hagaishapira requested changes
Please see that the manifests are missing outputs. Please address this and add relevant field to the output struct

2021-06-02 13:40 UTC, oriser requested changes

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/alert/acknowledge/acknowledge.go
delete empty line

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/alert/create/main.go
>  	})
That's not good, we should use only the SDK `env.Parse`, as it contains more than just calling this library.
Move that type of parsing func to the SDK

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/add-note/Dockerfile
> +FROM golang:1.16-alpine as builder
Change the entrypoint too

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/alert/create/Dockerfile
> +FROM golang:1.16-alpine as builder
Change the entrypoint

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/add-note/add-note.go
empty line

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/close/Dockerfile
> +FROM golang:1.16-alpine as builder
entrypoint

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/close/close.go
empty line

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/create/Dockerfile
> +FROM golang:1.16-alpine as builder
entrypoint

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/resolve/Dockerfile
> +FROM golang:1.16-alpine as builder
entrypoint

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/create/main.go
empty line

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/incident/resolve/resolve.go
empty lne

2021-06-02 13:40 UTC, oriser commented on steps/opsgenie/oncall/get/Dockerfile
> +FROM golang:1.16-alpine as builder
entrypoint

2021-06-14 14:43 UTC, hagaishapira requested changes
See comments

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/oncall/get/main.go
> +	stat := env.Parse(&o.args)
can return env.Parse directly

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/incident/resolve/resolve.go
> +	stat := env.Parse(&o.args)
return env.Parse directly

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/incident/create/main.go
> +	if err := incident.ValidatePriority(incident.Priority(o.args.Priority)); err != nil {
do you need this with the new oneof?

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/incident/create/main.go
> +	if err := incident.ValidatePriority(incident.Priority(o.args.Priority)); err != nil {
Check out the change I had here for the oneof in the PR I had, use what you've created in the SDK :)

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/incident/close/close.go
> +	stat := env.Parse(&o.args)
return Parse directly.

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/incident/add-note/add-note.go
> +	stat := env.Parse(&o.args)
return Parse directly

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/alert/create/main.go
> +	err := alert.ValidatePriority(alert.Priority(o.args.Priority))
can use oneof and change the manifest with the SDK validator.

2021-06-14 14:43 UTC, hagaishapira commented on steps/opsgenie/alert/acknowledge/acknowledge.go
> +	stat := env.Parse(&o.args)
return Parse directly

2021-06-14 14:50 UTC, nshem commented on steps/opsgenie/alert/create/main.go
> +	err := alert.ValidatePriority(alert.Priority(o.args.Priority))
one of is static. this is a dynamic validation.

2021-06-14 15:29 UTC, hagaishapira approved these changes
Update manifests and that's it

2021-06-15 07:55 UTC, oriser approved these changes

2021-06-15 07:58 UTC, merged