[SP-6256] Moving LogzIO step to new standard
stackpulse/steps pull request #122
Opened 2021-06-13 16:18 UTC by igorkheif

2021-06-13 17:09 UTC, eldadru commented on steps/logzio/base/base.go
> +func GetStatus(httpCode int) status.Status {
Sorry for jumping into this PR uninvited - this looks like a re-useable code - WDYT?

2021-06-13 18:00 UTC, igorkheif commented on steps/logzio/base/base.go
> +func GetStatus(httpCode int) status.Status {
It is, I am planning to move it later on somewhere more `common` (in fact the same code is used in different steps atm).

2021-06-14 07:46 UTC, hagaishapira commented on steps/logzio/base/base.go
> +		retStatus = status.New(codes.Internal, "coralogix has encountered an internal error", "")
This is logz. I think this is a good sign this code is similar :)

2021-06-14 07:46 UTC, hagaishapira requested changes
Fix type, other than that LGTM

2021-06-14 11:49 UTC, igorkheif commented on steps/logzio/base/base.go
> +		retStatus = status.New(codes.Internal, "coralogix has encountered an internal error", "")
True. Fixed!

2021-06-14 12:55 UTC, hagaishapira approved these changes
LGTM

2021-06-14 15:33 UTC, oriser approved these changes
Agree with @eldadru comment, we should move it to the SDK, other than that - LGTM

2021-06-14 15:37 UTC, merged