Okta virustotal greynoise steps
stackpulse/steps pull request #62
Opened 2021-05-04 02:38 UTC by tyliggity

- Sample responses:
  - virustotal
    - get-ip
```json
{
    "as_owner": "GOOGLE",
    "country": "US",
    "reputation": 304,
    "last_analysis_stats": {
        "harmless": 75,
        "malicious": 0,
        "suspicious": 0,
        "timeout": 0,
        "undetected": 9
    },
    "api_object": {
        "data": {
            "attributes": {
                "as_owner": "GOOGLE",
                "asn": 15169,
                "continent": "NA",
                "country": "US",
                "jarm": "29d3fd00029d29d00042d43d00041d598ac0c1012db967bb1ad0ff2491b3ae",
                "last_analysis_results": {
                    "ADMINUSLabs": {
                        "category": "harmless",
                        "engine_name": "ADMINUSLabs",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "AICC (MONITORAPP)": {
                        "category": "harmless",
                        "engine_name": "AICC (MONITORAPP)",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "AegisLab WebGuard": {
                        "category": "harmless",
                        "engine_name": "AegisLab WebGuard",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "AlienVault": {
                        "category": "harmless",
                        "engine_name": "AlienVault",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Antiy-AVL": {
                        "category": "harmless",
                        "engine_name": "Antiy-AVL",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Armis": {
                        "category": "harmless",
                        "engine_name": "Armis",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "AutoShun": {
                        "category": "undetected",
                        "engine_name": "AutoShun",
                        "method": "blacklist",
                        "result": "unrated"
                    },
                    "Avira": {
                        "category": "harmless",
                        "engine_name": "Avira",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "BADWARE.INFO": {
                        "category": "harmless",
                        "engine_name": "BADWARE.INFO",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Baidu-International": {
                        "category": "harmless",
                        "engine_name": "Baidu-International",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Bfore.Ai PreCrime": {
                        "category": "harmless",
                        "engine_name": "Bfore.Ai PreCrime",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "BitDefender": {
                        "category": "harmless",
                        "engine_name": "BitDefender",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Blueliv": {
                        "category": "harmless",
                        "engine_name": "Blueliv",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "CINS Army": {
                        "category": "harmless",
                        "engine_name": "CINS Army",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "CLEAN MX": {
                        "category": "harmless",
                        "engine_name": "CLEAN MX",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "CMC Threat Intelligence": {
                        "category": "harmless",
                        "engine_name": "CMC Threat Intelligence",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "CRDF": {
                        "category": "harmless",
                        "engine_name": "CRDF",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Certego": {
                        "category": "harmless",
                        "engine_name": "Certego",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Comodo Valkyrie Verdict": {
                        "category": "undetected",
                        "engine_name": "Comodo Valkyrie Verdict",
                        "method": "blacklist",
                        "result": "unrated"
                    },
                    "CyRadar": {
                        "category": "harmless",
                        "engine_name": "CyRadar",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Cyan": {
                        "category": "undetected",
                        "engine_name": "Cyan",
                        "method": "blacklist",
                        "result": "unrated"
                    },
                    "CyberCrime": {
                        "category": "harmless",
                        "engine_name": "CyberCrime",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "DNS8": {
                        "category": "harmless",
                        "engine_name": "DNS8",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Dr.Web": {
                        "category": "harmless",
                        "engine_name": "Dr.Web",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "ESET": {
                        "category": "harmless",
                        "engine_name": "ESET",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "ESTsecurity-Threat Inside": {
                        "category": "harmless",
                        "engine_name": "ESTsecurity-Threat Inside",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "EmergingThreats": {
                        "category": "harmless",
                        "engine_name": "EmergingThreats",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Emsisoft": {
                        "category": "harmless",
                        "engine_name": "Emsisoft",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "EonScope": {
                        "category": "harmless",
                        "engine_name": "EonScope",
                        "method": "blacklist",
                        "result": "clean"
                    },
                    "Forcepoint ThreatSeeker": {
                        "category": "harmless",
       [...]

2021-05-04 02:43 UTC, tyliggity commented
A couple of notes:
- On the Okta suspend user, the API gives the exact same error code and message if a user ID is either not found or if they are already suspended.  Therefore, it is only possible to return one of 2 states rather than one of the 3 originally proposed.  The invalid user state status is not possible to achieve from this API call alone as the API returns 404 and same message whether user is not found (invalid ID) or they are already suspended (invalid state).  So, I chose to go with invalid ID.
- On the Greynoise call, the API key is not necessary as we're using community edition (already not required per manifest)
- For Virustotal get-url call, we are really doing "get-domain", which is a synchronous call.  The get "url" call is actually not synchronous and instead the analysis is queued to be fetched at a later time.  Therefore, I went with the get domain call.

2021-05-05 15:06 UTC, hagaishapira requested changes

2021-05-05 15:06 UTC, hagaishapira commented on steps/virustotal/get-url/main.go
> +	reqURL := fmt.Sprintf("https://www.virustotal.com/api/v3/domains/%s", s.Url)
Did you consider using this?
https://github.com/VirusTotal/vt-go

2021-05-05 15:06 UTC, hagaishapira commented on steps/virustotal/get-url/main.go
> +		return step.ExitCodeFailure, nil, err
Do you have an example of the error message returned from the api here and whether is should be wrapped for human readability?

2021-05-05 15:06 UTC, hagaishapira commented on steps/virustotal/get-ip/main.go
> +	if err != nil {
What about non 2XX and Do you have an example of the error message returned from the api here and whether is should be wrapped for human readability?

2021-05-05 15:26 UTC, tyliggity commented on steps/greynoise/get-ip/main.go
> +	rawResp, err := http.Get(fmt.Sprintf("https://api.greynoise.io/v3/community/%s", s.Ip))
done

2021-05-05 15:29 UTC, tyliggity commented on steps/greynoise/get-ip/main.go
> +	if err != nil {
done

2021-05-05 15:32 UTC, tyliggity commented on steps/greynoise/get-ip/main.go
> +		return step.ExitCodeFailure, nil, err
done

2021-05-05 15:36 UTC, tyliggity commented on steps/okta/user/suspend/main.go
> +		return step.ExitCodeFailure, nil, err
Yes it's quite readable as the Okta HTTP client is a bit more friendly.  For example, it does return an error on 4xx responses whereas the Go default HTTP client does not.

Here is the full step output when invalid token OR invalid domain provided:
```
Step error: The API returned an error: Invalid token provided
```
My guess is that they do not return when invalid domain for security reasons so you cannot probe for Okta domains.

2021-05-05 15:42 UTC, tyliggity commented on steps/okta/user/suspend/main.go
> +	return step.ExitCodeOK, []byte(stepResultSuccess), nil
done

2021-05-05 15:45 UTC, tyliggity commented on steps/okta/user/suspend/main.go
> +		if resp.StatusCode == http.StatusNotFound {
Yes, in fact I would say it's more of an issue with their underlying API.  They essentially don't "see" the user anymore once the user is suspended.  The errors are exactly the same if invalid state or ID.  My guess is that in the unsuspend call you are explicitly looking for suspended users and of course the API can always see active users so both states must be considered, which is why it can come up as invalid state.

Okta does things like this for security I suppose.

2021-05-05 15:51 UTC, tyliggity commented on steps/virustotal/get-url/main.go
>  type VirustotalGetUrl struct {
done

2021-05-05 16:29 UTC, tyliggity commented on steps/virustotal/get-url/main.go
> +	reqURL := fmt.Sprintf("https://www.virustotal.com/api/v3/domains/%s", s.Url)
ok i switched to it but I'm not using `client.GetObject` for 2 reasons: first, you can't get the raw response from `GetObject`, and second they don't have options to return their own types (dumb) so you just get back this generic `*vt.Object` type that is a real pain to parse, which is way uglier than just parsing yourself especially in this case when the data we want back is already a nested object in the JSON.  Therefore, I'm using `client.Get`.

2021-05-05 16:31 UTC, tyliggity commented on steps/virustotal/get-url/main.go
> +		return step.ExitCodeFailure, nil, err
Now that we are using their sdk we do get a readable message:
```
Step error: Domain "www.google.foo" not found
```

2021-05-05 16:39 UTC, tyliggity commented on steps/virustotal/get-ip/main.go
> +	if err != nil {
Now that we are using their SDK we do get a human readable error message:
```
Step error: IP "8.8.8.8888" is not a valid IP address pattern
```

2021-05-06 07:51 UTC, hagaishapira commented on steps/virustotal/get-domain/manifest.yaml
>  outputs:
As I see the domain object has a reputation property I want to expose that in the output so please add
```suggestion
outputs:
- name: reputation
    description: "The reputation score for the domain in question."
    type: "int"
    example: 13
```

2021-05-06 07:52 UTC, hagaishapira requested changes
Please add reputation to the output of the VT get domain step as the domain object has that property vs the original URL object

2021-05-06 13:22 UTC, tyliggity commented on steps/virustotal/get-domain/manifest.yaml
>  outputs:
done

2021-05-06 13:40 UTC, hagaishapira approved these changes
LGTM

2021-05-06 13:42 UTC, merged