SP-6208: granfa get panel step
stackpulse/steps pull request #64
Opened 2021-05-05 11:30 UTC by itaischwartz

2021-05-05 14:23 UTC, kostyay commented on steps/grafana/get-panel/manifest.yaml
> +    type: "string"
this is not correct as your output goes to root

2021-05-05 14:24 UTC, kostyay approved these changes
fix the output and merge

2021-05-05 21:25 UTC, hagaishapira requested changes

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/main.go
> +	result := []byte(base64.StdEncoding.EncodeToString(output))
You are not using the outputs struct you've defined

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/main.go
> +		return step.ExitCodeFailure, nil, fmt.Errorf("get: %w", err)
What about a non 2XX response?

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/main.go
> +	err := envconf.Parse(&l.args)
Use https://github.com/stackpulse/steps-sdk-go/blob/master/env/parse Parse and not github.com/caarlos0/env/v6 directly

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/manifest.yaml
> +    example: "eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk"
This is not a valid key to the grafana url you've provided, right?

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/manifest.yaml
> +  - name: output
I prefer the field name to be more explicit and self explaining like "encoded_image"

2021-05-05 21:25 UTC, hagaishapira commented on steps/grafana/get-panel/manifest.yaml
> +  description: "Get a panel from grafana as PNG."
Perhaps expend on the fact that this uploads the panel to StackPulse's file storage and encodes the image as base64

2021-05-06 12:17 UTC, itaischwartz commented on steps/grafana/get-panel/main.go
> +	err := envconf.Parse(&l.args)
done

2021-05-06 12:19 UTC, itaischwartz commented on steps/grafana/get-panel/main.go
> +		return step.ExitCodeFailure, nil, fmt.Errorf("get: %w", err)
done

2021-05-06 12:19 UTC, itaischwartz commented on steps/grafana/get-panel/main.go
> +	result := []byte(base64.StdEncoding.EncodeToString(output))
done

2021-05-06 12:19 UTC, itaischwartz commented on steps/grafana/get-panel/manifest.yaml
> +    example: "eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk"
random key

2021-05-06 12:20 UTC, itaischwartz commented on steps/grafana/get-panel/manifest.yaml
> +  - name: output
done

2021-05-06 12:20 UTC, itaischwartz commented on steps/grafana/get-panel/manifest.yaml
> +    type: "string"
done

2021-05-06 14:14 UTC, hagaishapira approved these changes
Fix texts and last comment and MWG

2021-05-06 14:14 UTC, hagaishapira commented on steps/grafana/get-panel/manifest.yaml
> +  description: "Get a panel from grafana as PNG."
```suggestion
  description: "Get a panel from grafana using a Grafana Image Renderer url. The image will be uploaded to StackPulse's file storage and outputted from the step encoded to base64."
```

2021-05-06 14:14 UTC, hagaishapira commented on steps/grafana/get-panel/main.go
> +type Outputs struct {
delete this as you're not using it

2021-05-09 07:58 UTC, merged