Bluejeans meeting creation
stackpulse/steps pull request #78
Opened 2021-05-12 09:41 UTC by bogdanciobanu

Hi,
This is the first part of the PR. I've implemented the Bluejeans meeting creation. However, I have a few observations:
* I only implemented the Username + Password authentication. That's because when authenticating with client id + secret you get an enterprise id, not a user id and the meeting creation endpoint requires a user id (as you can see [here](https://bluejeans.github.io/api-rest-meetings/site/index.html). Some more info about the difference between auth methods can be found [here](https://support.bluejeans.com/s/article/Authentication-Methods-for-BlueJeans-Meetings-API-Endpoints)
** The [Python implementation](https://github.com/stackpulse/steps/blob/46025190efc65271d69dd255cf5bd761d7990edc/steps/bluejeans/meeting/create/doit.py) might be also broken. That's because `api_instance.get_token_by_client` and `api_instance.get_token_by_password` have different return types (long live strongly typed Go). If I'm missing some relevant info please let me know.
* I'd suggest also removing the ClientId and ClientSecret params. WDYT?

Please let me know if you have any feedback for the PR.

2021-05-12 09:45 UTC, bogdanciobanu commented
Here's an example running:
```
~/go/src/steps/steps/atlassian/jira/add-comment blue-jeans* ⇡ 10s ❯ docker run -e USERNAME=bgdn.ciobanu@gmail.com --env PASSWORD="usX0#gIL9t6Y\$pBu@#Q*" --env TITLE="FIRST_TRY" --env SEND_EMAIL="true" --env INVITEES="bgdn.ciobanu+1@gmail.com,bgdn.ciobanu@gmail.com" -it us-docker.pkg.dev/stackpulse/public/bluejeans/meeting/create:blue-jeans
{"api_response":"{\"id\":89624008,\"uuid\":\"44cb8f17-6efa-4b43-a45c-272105e46b28\",\"title\":\"FIRST_TRY\",\"description\":null,\"start\":1620812204000,\"end\":1620814904000,\"timezone\":\"Etc/GMT\",\"advancedMeetingOptions\":{\"videoBestFit\":false,\"publishMeeting\":false,\"encryptionType\":\"NO_ENCRYPTION\",\"moderatorLess\":false,\"allowStream\":false,\"autoRecord\":false,\"disallowChat\":false,\"muteParticipantsOnEntry\":false,\"showAllAttendeesInMeetingInvite\":false,\"meetingAccessType\":\"EVERYONE\",\"allowInterpreters\":false,\"waitingRoomAdmitSameEnterpriseUsers\":false,\"allowClosedCaptioning\":false,\"allowLiveTranscription\":false,\"videoMuteParticipantsOnEntry\":false,\"waitingRoomEnabled\":false,\"allowParticipantsStartScreenShare\":true,\"hasBreakoutRoomConfigs\":false,\"teleVisitEnabled\":false,\"allowHighlights\":false,\"allowModeratorScreenShare\":true,\"allowParticipantsHijackScreenShare\":true,\"editability\":{\"allowParticipantsHijackScreenShare\":true,\"waitingRoomEnabled\":false,\"autoRecord\":true,\"enforceMeetingEncryption\":true,\"addParticipantPasscode\":true,\"allowModeratorScreenShare\":true,\"allowHighlights\":true,\"teleVisitEnabled\":false,\"disallowChat\":true,\"allowInterpreters\":false,\"moderatorLess\":true,\"allowClosedCaptioning\":false,\"videoBestFit\":true,\"enforceMeetingEncryptionAllowPSTN\":true,\"hasBreakoutRoomConfigs\":true,\"waitingRoomAdmitSameEnterpriseUsers\":true,\"allowParticipantsStartScreenShare\":true,\"videoMuteParticipantsOnEntry\":true,\"allowLiveTranscription\":false,\"muteParticipantsOnEntry\":true,\"showAllAttendeesInMeetingInvite\":true}},\"notificationUrl\":null,\"notificationData\":null,\"moderator\":{\"id\":4693243,\"username\":\"bgdn.ciobanu\",\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},\"numericMeetingId\":\"903743086\",\"attendeePasscode\":\"2386\",\"addAttendeePasscode\":false,\"deleted\":false,\"allow720p\":false,\"status\":null,\"locked\":false,\"sequenceNumber\":0,\"icsUid\":\"G0sTI_W48D1VjyHU@oy9kAH7AyT8oMQY\",\"endPointType\":\"WEB_APP\",\"endPointVersion\":\"2.10\",\"attendees\":[{\"meeting\":{\"id\":89624008},\"email\":\"bgdn.ciobanu+1@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":0,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},{\"meeting\":{\"id\":89624008},\"email\":\"bgdn.ciobanu@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":4693243,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"}],\"isLargeMeeting\":false,\"created\":1620812204428,\"lastModified\":1620812204450,\"isExpired\":false,\"parentMeetingId\":null,\"parentMeetingUUID\":null,\"nextOccurrence\":null,\"timelessMeeting\":false,\"endlessMeeting\":false,\"first\":{\"start\":1620812204000,\"end\":1620814904000},\"last\":{\"start\":1620812204000,\"end\":1620814904000},\"next\":{\"start\":1620812204000,\"end\":1620814904000},\"nextStart\":1620812204000,\"nextEnd\":1620814904000,\"isPersonalMeeting\":false,\"inviteeJoinOption\":0,\"customMeetingProperties\":null}","meeting_url":"https://bluejeans.com/903743086"}
<-- END -->{"api_response":"{\"id\":89624008,\"uuid\":\"44cb8f17-6efa-4b43-a45c-272105e46b28\",\"title\":\"FIRST_TRY\",\"description\":null,\"start\":1620812204000,\"end\":1620814904000,\"timezone\":\"Etc/GMT\",\"advancedMeetingOptions\":{\"videoBestFit\":false,\"publishMeeting\":false,\"encryptionType\":\"NO_ENCRYPTION\",\"moderatorLess\":false,\"allowStream\":false,\"autoRecord\":false,\"disallowChat\":false,\"muteParticipantsOnEntry\":false,\"showAllAttendeesInMeetingInvite\":false,\"meetingAccessType\":\"EVERYONE\",\"allowInterpreters\":false,\"waitingRoomAdmitSameEnterpriseUsers\":false,\"allowClosedCaptioning\":false,\"allowLiveTranscription\":false,\"videoMuteParticipantsOnEntry\":false,\"waitingRoomEnabled\":false,\"allowParticipantsStartScreenShare\":true,\"hasBreakoutRoomConfigs\":false,\"teleVisitEnabled\":false,\"allowHighlights\":false,\"allowModeratorScreenShare\":true,\"allowParticipantsHijackScreenShare\":true,\"editability\":{\"allowParticipantsHijackScreenShare\":true,\"waitingRoomEnabled\":false,\"autoRecord\":true,\"enforceMeetingEncryption\":true,\"addParticipantPasscode\":true,\"allowModeratorScreenShare\":true,\"allowHighlights\":true,\"teleVisitEnabled\":false,\"disallowChat\":true,\"allowInterpreters\":false,\"moderatorLess\":true,\"allowClosedCaptioning\":false,\"videoBestFit\":true,\"enforceMeetingEncryptionAllowPSTN\":true,\"hasBreakoutRoomConfigs\":true,\"waitingRoomAdmitSameEnterpriseUsers\":true,\"allowParticipantsStartScreenShare\":true,\"videoMuteParticipantsOnEntry\":true,\"allowLiveTranscription\":false,\"muteParticipantsOnEntry\":true,\"showAllAttendeesInMeetingInvite\":true}},\"notificationUrl\":null,\"notificationData\":null,\"moderator\":{\"id\":4693243,\"username\":\"bgdn.ciobanu\",\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},\"numericMeetingId\":\"903743086\",\"attendeePasscode\":\"2386\",\"addAttendeePasscode\":false,\"deleted\":false,\"allow720p\":false,\"status\":null,\"locked\":false,\"sequenceNumber\":0,\"icsUid\":\"G0sTI_W48D1VjyHU@oy9kAH7AyT8oMQY\",\"endPointType\":\"WEB_APP\",\"endPointVersion\":\"2.10\",\"attendees\":[{\"meeting\":{\"id\":89624008},\"email\":\"bgdn.ciobanu+1@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":0,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},{\"meeting\":{\"id\":89624008},\"email\":\"bgdn.ciobanu@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":4693243,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"}],\"isLargeMeeting\":false,\"created\":1620812204428,\"lastModified\":1620812204450,\"isExpired\":false,\"parentMeetingId\":null,\"parentMeetingUUID\":null,\"nextOccurrence\":null,\"timelessMeeting\":false,\"endlessMeeting\":false,\"first\":{\"start\":1620812204000,\"end\":1620814904000},\"last\":{\"start\":1620812204000,\"end\":1620814904000},\"next\":{\"start\":1620812204000,\"end\":1620814904000},\"nextStart\":1620812204000,\"nextEnd\":1620814904000,\"isPersonalMeeting\":false,\"inviteeJoinOption\":0,\"customMeetingProperties\":null}","meeting_url":"https://bluejeans.com/903743086"}%
```
And the meeting:
![Screen Shot 2021-05-12 at 12 44 03 PM](https://user-images.githubusercontent.com/3052787/117954607-db53ea80-b31f-11eb-908a-e28d57604a29.png)

2021-05-12 11:34 UTC, bogdanciobanu commented
I've also added the other two steps. Here are example runs:
* for list
```~/go/src/steps blue-jeans* ❯ docker run --env HEROKU_API_KEY=*** --env APP_ID=serene-everglades-83021 -it us-docker.pkg.dev/stackpulse/public/heroku/release/list:blue-jeans                           14:27:38
{"releases":"[{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:00:51Z\",\"current\":false,\"description\":\"Initial release\",\"id\":\"3f8b9436-e65b-4334-8a32-2d62668cd108\",\"output_stream_url\":null,\"slug\":null,\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:00:51Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":1},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:00:52Z\",\"current\":false,\"description\":\"Enable Logplex\",\"id\":\"598b6ee8-a637-4f20-8ab7-6a81f64ecb30\",\"output_stream_url\":null,\"slug\":null,\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:00:52Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":2},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:01:24Z\",\"current\":false,\"description\":\"Deploy b7ec67bd\",\"id\":\"1de6f7ac-5129-4205-98ef-180114706e0a\",\"output_stream_url\":null,\"slug\":{\"id\":\"4d457deb-1644-4c9f-b2ad-7b811a012c52\"},\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:01:24Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":3},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:07:11Z\",\"current\":true,\"description\":\"Deploy 447e84e9\",\"id\":\"2cddad47-f5b4-4c25-9006-2a7a15fbc8bd\",\"output_stream_url\":null,\"slug\":{\"id\":\"6a480a02-fca4-486f-978c-f8708455a59f\"},\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:07:11Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":4}]"}
<-- END -->{"releases":"[{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:00:51Z\",\"current\":false,\"description\":\"Initial release\",\"id\":\"3f8b9436-e65b-4334-8a32-2d62668cd108\",\"output_stream_url\":null,\"slug\":null,\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:00:51Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":1},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:00:52Z\",\"current\":false,\"description\":\"Enable Logplex\",\"id\":\"598b6ee8-a637-4f20-8ab7-6a81f64ecb30\",\"output_stream_url\":null,\"slug\":null,\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:00:52Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":2},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:01:24Z\",\"current\":false,\"description\":\"Deploy b7ec67bd\",\"id\":\"1de6f7ac-5129-4205-98ef-180114706e0a\",\"output_stream_url\":null,\"slug\":{\"id\":\"4d457deb-1644-4c9f-b2ad-7b811a012c52\"},\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:01:24Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":3},{\"addon_plan_names\":[],\"app\":{\"id\":\"5c7474a8-ea70-42a3-9e6d-13cc757a0c41\",\"name\":\"serene-everglades-83021\"},\"created_at\":\"2021-05-12T11:07:11Z\",\"current\":true,\"description\":\"Deploy 447e84e9\",\"id\":\"2cddad47-f5b4-4c25-9006-2a7a15fbc8bd\",\"output_stream_url\":null,\"slug\":{\"id\":\"6a480a02-fca4-486f-978c-f8708455a59f\"},\"status\":\"succeeded\",\"updated_at\":\"2021-05-12T11:07:11Z\",\"user\":{\"email\":\"bgdn.ciobanu@gmail.com\",\"id\":\"92ae3c45-5fbb-4f11-a962-20825f2651dd\"},\"version\":4}]"}% ```
* and for rollback

2021-05-19 12:01 UTC, hagaishapira commented
Hi @bogdanciobanu,
Let me first apologize for taking so long to get back to you.
Regarding the client id/secret authentication you are correct and we will need to implement a 3legged auth flow which will generate an auth token that will be passed to step if a username and password are not given.
We will need to change the interface to have to something like this in addition to the username and password approach (the step should use the username and password if given and if not attempt to use the token).
```golang
type Args struct {
	BlueJeansToken string `env:"BLUEJEANS_TOKEN"`
}
...
func (b *BlueJeansMeetingCreate) Init() error {
	if err := json.Unmarshal([]byte(z.args.BlueJeansToken), &b.token); err != nil {
		return fmt.Errorf("unmarshal token: %w", err)
	}
    // TODO:
    // extract user id from token.raw
    // check for sufficient permissions 
}
func (b *BlueJeansMeetingCreate) Run() error {
	client := oauth2.NewClient(context.Background(), oauth2.StaticTokenSource(b.token))
    // TODO:
    // CreateMeeting
}
```

You can also see example of this in the [zoom create meeting step ](https://github.com/stackpulse/steps/blob/master/steps/zoom/meeting/create/main.go)

2021-05-19 12:03 UTC, hagaishapira commented on steps/bluejeans/meeting/create/manifest.yaml
> +    required: false
```suggestion
  - name: BLUJEANS_TOKEN
    type: string
    description: "Marshalled json of a oauth token."
    required: false
```

2021-05-19 14:28 UTC, hagaishapira commented
btw this is how that auth token looks like from the BlueJeans API.
![image (13)](https://user-images.githubusercontent.com/29172759/118829818-1f6a6080-b8c7-11eb-90d2-59e8a07f8c36.png)
We of course pass it into the steps as a golang oauth2 token https://github.com/golang/oauth2/blob/master/token.go

2021-05-19 15:32 UTC, bogdanciobanu commented
@hagaishapira please take another look. I've updated the Bluejeans step to use the token if the username and password are missing. I didn't validate the token since I couldn't get an example with the permissions populated and anyway the API is validating the token.

2021-05-19 21:23 UTC, hagaishapira requested changes
Reviewed the Heroku steps while @itaischwartz will review the bluejeans work.
Had a few comments mostly regarding to error handling and making sure those are indicative and readable for users and the outputs.

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +		return step.ExitCodeFailure, nil, err
We need to make sure this error is human readable

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/rollback/main.go
> +		Status: release.Status,
What about the api_object field?

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/manifest.yaml
> +  - name: api_response
```suggestion
  - name: api_object
```

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/rollback/manifest.yaml
> +  - name: api_response
```suggestion
  - name: api_object
```

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +	jsonOutput, err := json.Marshal(&output{Releases: string(jsonReleases)})
what about the api_objects field

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +	jsonReleases, err := json.Marshal(releaseList)
please the expected releases field format from the manifest, it should be an array of objects containing ids, descriptions, and perhaps also version and not just the raw objects from the api response.

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +}
```suggestion
type release struct {
         description string
         id string
         status string
         current bool
         version int
}

type output struct {
	Releases []release `json:"releases"`
	step.Outputs
}
```

2021-05-19 21:23 UTC, hagaishapira commented on steps/heroku/release/list/manifest.yaml
> +        }
```suggestion
        {
          "id":"e8c2f512-aac8-4aed-ad6b-b5ce5c9e6d1e",
          "description": "deploy tag 5386734",
          "status": "succeeded",
          "current": true,
          "version": 2
        },
        {
          "id":"e6f4f512-aac8-4aed-ad6b-b5ce5c9e5d1e",
          "description": "change env var API_KEY",
          "current": false,
          "status": "succeeded",
          "version": 1
        }
```

2021-05-20 12:36 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return fmt.Errorf("Error logging in with username and password: %w", err)
use lower case for errors

2021-05-20 12:37 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return err
```suggestion
		return fmt.Errorf("jsonMarshal: %w", err)
```

2021-05-20 12:38 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return fmt.Errorf("Error logging in with username and password: %w", err)
```suggestion
		return fmt.Errorf("logging in with username and password: %w", err)
```

2021-05-20 12:38 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return fmt.Errorf("Error reading response body: %w", err)
```suggestion
		return fmt.Errorf("read response body: %w", err)
```

2021-05-20 12:39 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +	if resp.StatusCode >= 300 {
```suggestion
	if resp.StatusCode/100 != 2 {
```

2021-05-20 12:41 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return fmt.Errorf("Error logging in with username and password: %s", body)
```suggestion
		return fmt.Errorf("got non 20X HTTP response code: %d(%s)", resp.StatusCode, resp.Status)
```

2021-05-20 12:47 UTC, itaischwartz commented on steps/bluejeans/meeting/create/main.go
> +			return step.ExitCodeFailure, nil, err
```suggestion
			return step.ExitCodeFailure, nil, fmt.Errorf("loginPassword: %w", err)
```

2021-05-20 12:52 UTC, itaischwartz commented on steps/bluejeans/meeting/create/main.go
> +		return step.ExitCodeFailure, nil, fmt.Errorf("Missing credentials")
```suggestion
		return step.ExitCodeFailure, nil, fmt.Errorf("invalid arguments. username and password or token are requried.")
```

2021-05-20 12:53 UTC, itaischwartz commented on steps/bluejeans/meeting/create/main.go
> +		return step.ExitCodeFailure, nil, err
```suggestion
		return step.ExitCodeFailure, nil, fmt.Errorf("jsonMarshal: %w", err)
```

2021-05-20 12:54 UTC, itaischwartz commented on steps/bluejeans/meeting/create/main.go
> +
maybe check here that we got username+password OR token and fail fast with invalid argument error

2021-05-20 13:01 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +	if resp.StatusCode >= 300 {
```suggestion
	if resp.StatusCode >= 300 {	if resp.StatusCode/100 != 2 {
```

2021-05-20 13:02 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +	for _, email := range strings.Split(invitees, ",") {
no need, just pass []string and let env.parse do the work

2021-05-20 13:02 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return nil, "", err
```suggestion
		return nil, "", fmt.errorf("jsonMarshal: %w", error)
```

2021-05-20 13:03 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return nil, "", fmt.Errorf("Error creating meeting: %w", err)
```suggestion
		return nil, "", fmt.Errorf("scheduledMeeting: %w", err)
```

2021-05-20 13:04 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return nil, "", fmt.Errorf("Error reading response body: %w", err)
```suggestion
		return nil, "", fmt.Errorf("read body: %w", err)
```

2021-05-20 13:05 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +		return nil, "", fmt.Errorf("Error unmarshalling meeting: %w", err)
```suggestion
		return nil, "", fmt.Errorf("unmarshalMeeting: %w", err)
```

2021-05-20 13:05 UTC, itaischwartz commented on steps/bluejeans/base/base.go
> +	return body, meetingUrl, err
```suggestion
	return body, meetingUrl, nil
```

2021-05-20 13:07 UTC, itaischwartz commented on steps/bluejeans/meeting/create/manifest.yaml
> +    description: "Marshalled json of a oauth token."
```suggestion
    description: "Marshalled JSON of an OAuth token."
```

2021-05-20 13:11 UTC, itaischwartz requested changes
great work!
I prefer using short, lowercase messages for error, and always wrap errors with fmt.Errorf on caller.

2021-05-20 15:45 UTC, bogdanciobanu commented on steps/heroku/release/list/main.go
> +	jsonOutput, err := json.Marshal(&output{Releases: string(jsonReleases)})
Since I was mistaken and returning the raw api objects I thought it makes no sense to include that one too. Added it now. Thanks for pointing it out 🙌

2021-05-21 07:08 UTC, bogdanciobanu commented
@hagaishapira @itaischwartz please take another look

2021-05-23 05:57 UTC, hagaishapira reviewed
Hi Bogdan see some minor changes but overall looks really good. Did you run all of these again to check they operate and output as expected?

2021-05-23 05:57 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +	jsonOutput, err := json.Marshal(&output{Releases: releases, APIResponse: string(jsonAPIResponse)})
Update to populate `Object` from `step.Outputs`

2021-05-23 05:57 UTC, hagaishapira commented on steps/heroku/release/list/main.go
> +	APIResponse string    `json:"api_response"`
Hi @bogdanciobanu, please see you shouldn't declare `api_response` but use `api_object` which is embedded form `step.Outputs`

2021-05-23 05:57 UTC, hagaishapira commented on steps/heroku/release/list/manifest.yaml
> +  - name: api_response
update as `api_response` is a mistake in the original manifest

2021-05-23 05:57 UTC, hagaishapira commented on steps/heroku/release/rollback/main.go
> +	APIObject string `json:"api_object"`
same as before with using this field from `step.Outputs`

2021-05-23 05:57 UTC, hagaishapira commented on steps/heroku/release/rollback/main.go
> +		APIObject: string(jsonAPIObject),
Populate `Object` from step.Outputs which is an interface{}

2021-05-23 14:56 UTC, bogdanciobanu commented
@hagaishapira PTAL

2021-05-23 14:59 UTC, bogdanciobanu commented
QA results:
Bluejeans meeting create
```
~/go/src/steps blue-jeans* 12s ❯ docker run -e USERNAME=bgdn.ciobanu@gmail.com --env PASSWORD="***" --env TITLE="FIRST_TRY" --env SEND_EMAIL="true" --env INVITEES="bgdn.ciobanu+1@gmail.com,bgdn.ciobanu@gmail.com" -it us-docker.pkg.dev/stackpulse/public/bluejeans/meeting/create:blue-jeans
{"meeting_url":"https://bluejeans.com/345563910","api_object":"{\"id\":90191080,\"uuid\":\"0f4b1098-e3aa-41f7-a7ba-e1d8d7d1ada2\",\"title\":\"FIRST_TRY\",\"description\":null,\"start\":1621781576000,\"end\":1621784276000,\"timezone\":\"Etc/GMT\",\"advancedMeetingOptions\":{\"videoBestFit\":false,\"publishMeeting\":false,\"encryptionType\":\"NO_ENCRYPTION\",\"moderatorLess\":false,\"allowStream\":false,\"autoRecord\":false,\"disallowChat\":false,\"muteParticipantsOnEntry\":false,\"showAllAttendeesInMeetingInvite\":false,\"meetingAccessType\":\"EVERYONE\",\"allowInterpreters\":false,\"waitingRoomAdmitSameEnterpriseUsers\":false,\"allowClosedCaptioning\":false,\"allowLiveTranscription\":false,\"videoMuteParticipantsOnEntry\":false,\"waitingRoomEnabled\":false,\"allowParticipantsStartScreenShare\":true,\"hasBreakoutRoomConfigs\":false,\"teleVisitEnabled\":false,\"allowHighlights\":false,\"allowModeratorScreenShare\":true,\"allowParticipantsHijackScreenShare\":true,\"editability\":{\"allowParticipantsHijackScreenShare\":true,\"waitingRoomEnabled\":false,\"autoRecord\":true,\"enforceMeetingEncryption\":true,\"addParticipantPasscode\":true,\"allowModeratorScreenShare\":true,\"allowHighlights\":true,\"teleVisitEnabled\":false,\"disallowChat\":true,\"allowInterpreters\":false,\"moderatorLess\":true,\"allowClosedCaptioning\":false,\"videoBestFit\":true,\"enforceMeetingEncryptionAllowPSTN\":true,\"hasBreakoutRoomConfigs\":true,\"waitingRoomAdmitSameEnterpriseUsers\":true,\"allowParticipantsStartScreenShare\":true,\"videoMuteParticipantsOnEntry\":true,\"allowLiveTranscription\":false,\"muteParticipantsOnEntry\":true,\"showAllAttendeesInMeetingInvite\":true}},\"notificationUrl\":null,\"notificationData\":null,\"moderator\":{\"id\":4693243,\"username\":\"bgdn.ciobanu\",\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},\"numericMeetingId\":\"345563910\",\"attendeePasscode\":\"0955\",\"addAttendeePasscode\":false,\"deleted\":false,\"allow720p\":false,\"status\":null,\"locked\":false,\"sequenceNumber\":0,\"icsUid\":\"OYRGa_GBg8Iw7cEC@8Z9gWBUimCl9KRb\",\"endPointType\":\"WEB_APP\",\"endPointVersion\":\"2.10\",\"attendees\":[{\"meeting\":{\"id\":90191080},\"email\":\"bgdn.ciobanu+1@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":0,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},{\"meeting\":{\"id\":90191080},\"email\":\"bgdn.ciobanu@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":4693243,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"}],\"isLargeMeeting\":false,\"created\":1621781576252,\"lastModified\":1621781576261,\"isExpired\":false,\"parentMeetingId\":null,\"parentMeetingUUID\":null,\"nextOccurrence\":null,\"timelessMeeting\":false,\"endlessMeeting\":false,\"first\":{\"start\":1621781576000,\"end\":1621784276000},\"last\":{\"start\":1621781576000,\"end\":1621784276000},\"next\":{\"start\":1621781576000,\"end\":1621784276000},\"nextStart\":1621781576000,\"nextEnd\":1621784276000,\"isPersonalMeeting\":false,\"inviteeJoinOption\":0,\"customMeetingProperties\":null}"}
<-- END -->{"meeting_url":"https://bluejeans.com/345563910","api_object":"{\"id\":90191080,\"uuid\":\"0f4b1098-e3aa-41f7-a7ba-e1d8d7d1ada2\",\"title\":\"FIRST_TRY\",\"description\":null,\"start\":1621781576000,\"end\":1621784276000,\"timezone\":\"Etc/GMT\",\"advancedMeetingOptions\":{\"videoBestFit\":false,\"publishMeeting\":false,\"encryptionType\":\"NO_ENCRYPTION\",\"moderatorLess\":false,\"allowStream\":false,\"autoRecord\":false,\"disallowChat\":false,\"muteParticipantsOnEntry\":false,\"showAllAttendeesInMeetingInvite\":false,\"meetingAccessType\":\"EVERYONE\",\"allowInterpreters\":false,\"waitingRoomAdmitSameEnterpriseUsers\":false,\"allowClosedCaptioning\":false,\"allowLiveTranscription\":false,\"videoMuteParticipantsOnEntry\":false,\"waitingRoomEnabled\":false,\"allowParticipantsStartScreenShare\":true,\"hasBreakoutRoomConfigs\":false,\"teleVisitEnabled\":false,\"allowHighlights\":false,\"allowModeratorScreenShare\":true,\"allowParticipantsHijackScreenShare\":true,\"editability\":{\"allowParticipantsHijackScreenShare\":true,\"waitingRoomEnabled\":false,\"autoRecord\":true,\"enforceMeetingEncryption\":true,\"addParticipantPasscode\":true,\"allowModeratorScreenShare\":true,\"allowHighlights\":true,\"teleVisitEnabled\":false,\"disallowChat\":true,\"allowInterpreters\":false,\"moderatorLess\":true,\"allowClosedCaptioning\":false,\"videoBestFit\":true,\"enforceMeetingEncryptionAllowPSTN\":true,\"hasBreakoutRoomConfigs\":true,\"waitingRoomAdmitSameEnterpriseUsers\":true,\"allowParticipantsStartScreenShare\":true,\"videoMuteParticipantsOnEntry\":true,\"allowLiveTranscription\":false,\"muteParticipantsOnEntry\":true,\"showAllAttendeesInMeetingInvite\":true}},\"notificationUrl\":null,\"notificationData\":null,\"moderator\":{\"id\":4693243,\"username\":\"bgdn.ciobanu\",\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},\"numericMeetingId\":\"345563910\",\"attendeePasscode\":\"0955\",\"addAttendeePasscode\":false,\"deleted\":false,\"allow720p\":false,\"status\":null,\"locked\":false,\"sequenceNumber\":0,\"icsUid\":\"OYRGa_GBg8Iw7cEC@8Z9gWBUimCl9KRb\",\"endPointType\":\"WEB_APP\",\"endPointVersion\":\"2.10\",\"attendees\":[{\"meeting\":{\"id\":90191080},\"email\":\"bgdn.ciobanu+1@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":0,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"},{\"meeting\":{\"id\":90191080},\"email\":\"bgdn.ciobanu@gmail.com\",\"followupEmailSentDate\":null,\"inviteeid\":4693243,\"firstname\":\"\",\"lastname\":\"\",\"profile_pic_url\":\"\"}],\"isLargeMeeting\":false,\"created\":1621781576252,\"lastModified\":1621781576261,\"isExpired\":false,\"parentMeetingId\":null,\"parentMeetingUUID\":null,\"nextOccurrence\":null,\"timelessMeeting\":false,\"endlessMeeting\":false,\"first\":{\"start\":1621781576000,\"end\":1621784276000},\"last\":{\"start\":1621781576000,\"end\":1621784276000},\"next\":{\"start\":1621781576000,\"end\":1621784276000},\"nextStart\":1621781576000,\"nextEnd\":1621784276000,\"isPersonalMeeting\":false,\"inviteeJoinOption\":0,\"customMeetingProperties\":null}"}%
```

It's important to note that I didn't test the token verison.

2021-05-23 15:13 UTC, hagaishapira approved these changes

2021-05-24 08:03 UTC, merged