SP-6203-store-expose-step-exeucution-error
stackpulse/steps pull request #84
Opened 2021-05-18 16:13 UTC by talbe

2021-05-18 16:17 UTC, kostyay commented on steps/redis/get/main.go
> +		return &step.Error{Code: step.InvalidArgument, Message: "invalid env vars provided", Verbose: fmt.Errorf("error: %w", err).Error()}
```suggestion
		return &step.Error{Code: step.InvalidArgument, Message: "Environment variables are missing or invalid", Verbose: fmt.Errorf("error: %w", err).Error()}
```

2021-05-18 16:17 UTC, kostyay commented on steps/redis/get/main.go
> +		return &step.Error{Code: step.Unavailable, Message: "failed connect redis client", Verbose: fmt.Errorf("error: %w", err).Error()}
```suggestion
		return &step.Error{Code: step.Unavailable, Message: "Failed connecting to redis server", Verbose: fmt.Errorf("error: %w", err).Error()}
```

2021-05-18 16:19 UTC, kostyay commented on steps/redis/get/main.go
> +		return nil, &step.Error{Code: step.InvalidArgument, Message: "invalid result returned from get operation"}
im not sure InvalidArgument is the right status for this error
maybe Internal?

2021-05-18 16:20 UTC, kostyay commented on steps/redis/get/main.go
> +		return nil, &step.Error{Code: step.InvalidArgument, Message: "failed getting key value", Verbose: fmt.Sprintf("validate key is valid: %w", err)}
```suggestion
		return nil, &step.Error{Code: step.InvalidArgument, Message: "failed getting key value", Verbose: fmt.Sprintf("validate key is valid: %s", err.Error())}
```
Cant use %w outside of fmt.Errorf

2021-05-18 16:21 UTC, kostyay commented on steps/redis/get/main.go
> +	}
what is the purpose of this? i dont think that u need it

2021-05-18 16:21 UTC, kostyay requested changes
see comments

2021-05-18 16:22 UTC, kostyay commented on steps/redis/get/main.go
> +func (l *RedisGet) Run() (outputJson step.Output, stepError *step.Error) {
```suggestion
func (l *RedisGet) Run() (step.Output, *step.Error) {
```

2021-05-20 16:25 UTC, hagaishapira reviewed
Please also update the cookiecutter template located at scripts/step-template

2021-05-20 16:25 UTC, hagaishapira commented on steps/redis/get/Dockerfile
> +ENTRYPOINT ["/bin/sh", "-c", "/${STEP_NAME}"]
Should we do this change to all dockerfiles who use the new sdk?

2021-05-20 19:34 UTC, hagaishapira commented on steps/redis/get/Dockerfile
> +ENTRYPOINT ["/bin/sh", "-c", "/${STEP_NAME}"]
@kostyay @talbe ?

2021-05-23 12:44 UTC, talbe commented on steps/redis/get/Dockerfile
> +ENTRYPOINT ["/bin/sh", "-c", "/${STEP_NAME}"]
@hagaishapira Yeah, sp-base-step is redundant

2021-05-24 15:54 UTC, hagaishapira approved these changes
LGTM

2021-05-24 15:55 UTC, merged