SP-6320 zoom revamp & tests
stackpulse/steps pull request #92
Opened 2021-05-24 11:53 UTC by nshem

2021-05-24 15:34 UTC, oriser reviewed
Small comments

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +			return nil, status.FromError(codes.Internal, "Failed to unmarshal response", err)
No need for "Failed", "Error", etc in error messages
```suggestion
			return nil, status.FromError(codes.Internal, "unmarshal response", err)
```

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +		return nil, status.FromError(codes.Internal, "Failed to create meeting", apiError)
```suggestion
		return nil, status.FromError(codes.Internal, "create meeting", apiError)
```

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +func (z *ZoomMeetingCreate) DeprecatedRun() (exitCode int, output zoom.Meeting, err error) {
Convert the return values of this function to output and status, it will be clearer for new eyes coming for this step

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +		return nil, status.FromError(codes.Internal, "Failed to read response body", err)
```suggestion
		return nil, status.FromError(codes.Internal, "read response body", err)
```

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +		return nil, status.FromError(codes.Internal, "Failed to marshal params", err)
```suggestion
		return nil, status.FromError(codes.Internal, "marshal params", err)
```

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +		return nil, status.FromError(codes.Internal, "Failed to post request", err)
```suggestion
		return nil, status.FromError(codes.Internal, "post request", err)
```

2021-05-24 15:34 UTC, oriser commented on steps/zoom/meeting/create/main.go
> +		return status.FromError(codes.Unauthenticated, "Failed to unmarshal zoom token", err)
```suggestion
		return status.FromError(codes.Unauthenticated, "unmarshal zoom token", err)
```

2021-05-24 19:29 UTC, eldadru commented
@nshem i understood we have a backwards compatibility issue here, lets discuss that before merging.

2021-05-25 08:28 UTC, hagaishapira commented
Also please update the manifest, it is not up to current convention, doesn't have separated fields, or the api_object

2021-05-25 12:07 UTC, hagaishapira commented on steps/zoom/meeting/create/main.go
>  	if err != nil {
What about checking for non-2XX status codes. I see the API can return 300 if rate limit for the day was reached 
https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate

2021-05-30 08:53 UTC, hagaishapira requested changes
See non resolved issues

2021-05-30 08:53 UTC, hagaishapira commented on steps/zoom/meeting/create/main.go
> +		return nil, nil, status.FromError(codes.Unavailable, "post request", err)
Do we have here specific response errors we can map? What about checking for non-2XX statuses?

2021-05-30 08:53 UTC, hagaishapira commented on steps/zoom/meeting/create/main.go
>  	if err != nil {
Here already said this and it wasn't resolved.

2021-05-30 09:13 UTC, nshem commented on steps/zoom/meeting/create/main.go
> +	if statusCode == http.StatusNotFound {
@hagaishapira

2021-05-30 09:14 UTC, nshem commented on steps/zoom/meeting/create/main.go
>  	if err != nil {
@hagaishapira https://github.com/stackpulse/steps/pull/92#discussion_r642046050

2021-05-30 09:26 UTC, hagaishapira commented on steps/zoom/meeting/create/main.go
> +		return nil, status.FromError(codes.Aborted, "to many requests per day", apiError)
```suggestion
		return nil, status.FromError(codes.Aborted, "daily requests limit exceeded", apiError)
```

2021-05-30 10:17 UTC, hagaishapira approved these changes
LGTM, please have @oriser approve before commiting

2021-05-30 10:41 UTC, oriser approved these changes
LGTM

2021-05-30 10:57 UTC, merged