[SP-6317] RabbitMQ steps refactor and tests
stackpulse/steps pull request #93
Opened 2021-05-24 11:56 UTC by oriser

2021-05-24 12:32 UTC, hagaishapira commented
Please also have someone else from RnD to review your tests and code

2021-05-25 08:22 UTC, hagaishapira reviewed
What about manifests? They don't have outputs

2021-05-25 08:22 UTC, hagaishapira commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, fmt.Sprintf("parsing response body as JSON: %s", err.Error()), fmt.Sprintf("original response: %s", string(body)))
Are we sure printing the json parsing error here is user friendly enough to be in the message and not verbose?

2021-05-25 08:22 UTC, hagaishapira commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "sending HTTP request", err.Error())
This isn't necessarily internal

2021-05-25 12:14 UTC, kostyay commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "create new HTTP request", err.Error())
```suggestion
		return nil, status.FromError(codes.Internal, "create new HTTP request", err)
```

2021-05-25 12:14 UTC, hagaishapira commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "sending HTTP request", err.Error())
What about checking for non-2XX responses? what can those mean/be so that we can return valuable error to the users?

2021-05-25 12:14 UTC, kostyay commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "sending HTTP request", err.Error())
handle known http status codes

2021-05-25 12:15 UTC, kostyay commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, fmt.Sprintf("parsing response body as JSON: %s", err.Error()), fmt.Sprintf("original response: %s", string(body)))
id use "Failed parsing RabbitMQ response" for the friendly error message

2021-05-25 12:15 UTC, kostyay commented on steps/rabbitmq/base/base.go
> +	return retGc.Data().(map[string]interface{}), status.OK
```suggestion
	return retGc.Data().(step.Output), status.OK
```

2021-05-25 13:11 UTC, kostyay requested changes
* Update Dockerfile entrypoint
* Update go to 1.16 (Dockerfile + go.mod)
* Move common testing logic to common folder. It seems like there are many tests that repeat each other, there is no point copy-pasting them. You can define common tests array in common directory and inject the test cases into each specific step's intergration test

2021-05-25 13:11 UTC, kostyay commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "reading response body", err.Error())
FromError

2021-05-25 13:11 UTC, kostyay commented on steps/rabbitmq/consumers/consumers_integration_test.go
> +			WantExitCode: 1,
```suggestion
			WantExitCode: exec.StepExecFailed,
```

2021-05-25 14:02 UTC, oriser commented on steps/rabbitmq/base/base.go
> +		return nil, status.New(codes.Internal, "sending HTTP request", err.Error())
@kostyay @hagaishapira I think that should be in the SDK, WDYT?
Returning the correct status code depends on the HTTP status

2021-05-25 16:20 UTC, oriser commented on steps/rabbitmq/channels/channels_integration_test.go
> +	time.Sleep(10 * time.Second)
I reduced it to 3 seconds, I can maybe polling the Rabbit server but it sounds overkill for a test

2021-05-25 16:21 UTC, oriser commented on steps/rabbitmq/base/base.go
> +	return retGc.Data().(map[string]interface{}), status.OK
It causes problems, the calling function then casting it to step.Output

2021-05-26 12:02 UTC, kostyay commented on steps/rabbitmq/queues/top/analayze.go
> +			return status.FromError(codes.Internal, fmt.Sprintf("invalid exclude regex: %q", r.excludeRe), err)
```suggestion
			return status.FromError(codes.InvalidArguments, fmt.Sprintf("invalid exclude regex: %q", r.excludeRe), err)
```

2021-05-26 12:04 UTC, kostyay approved these changes
fix comment

2021-05-26 13:00 UTC, hagaishapira approved these changes
See issues

2021-05-26 13:00 UTC, hagaishapira commented on steps/rabbitmq/base/base.go
> +		return nil, status.FromError(codes.Internal, "sending HTTP request", err)
what about checking for non-2xx status?

2021-05-26 13:00 UTC, hagaishapira commented on steps/rabbitmq/base/base.go
> +		return nil, status.FromError(codes.Internal, "create new HTTP request", err)
```suggestion
		return nil, status.FromError(codes.InvalidArguments, "create new HTTP request", err)
```

2021-05-26 13:20 UTC, oriser commented on steps/rabbitmq/base/base.go
> +		return nil, status.FromError(codes.Internal, "sending HTTP request", err)
We will add a generic method for that in the status SDK, which return the right status code according to the http status code

2021-05-26 14:21 UTC, merged