[SP-5461]
stackpulse/steps pull request #94
Opened 2021-05-25 07:31 UTC by InbarPerry

2021-05-25 07:58 UTC, moshebe approved these changes

2021-05-25 07:58 UTC, moshebe commented on steps/http/request/go.mod
> +//replace github.com/stackpulse/steps-sdk-go v0.0.0-20210513120802-a8b66edfdab8 => ../../../../steps-sdk-go
remove comment if not necessary

2021-05-25 07:58 UTC, moshebe commented on steps/http/request/input.go
> +	"github.com/stackpulse/steps-sdk-go/codes"
goimports

2021-05-25 07:58 UTC, moshebe commented on steps/http/request/main.go
> +	"github.com/stackpulse/steps-sdk-go/codes"
goimports

2021-05-25 12:16 UTC, hagaishapira commented on steps/http/request/input_test.go
> +}
What about integration tests?

2021-05-27 08:55 UTC, hagaishapira requested changes
See comments

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +  description: "Send HTTP request."
```suggestion
  description: "Send an HTTP request."
```

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +    description: "URL of the request. If scheme is not found, HTTPS:// will be used by default."
```suggestion
    description: "URL of the request. If a scheme is not found, HTTPS:// will be used by default."
```

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +      description: "Authentication type."
Until we have an enum type for env vars please explain possible types and dependencies.

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +    description: "Headers of the request."
How to specify headers? Example?

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +  - name: header
headers?

2021-05-27 08:55 UTC, hagaishapira commented on steps/http/request/manifest.yaml
> +    description: "Body as received in the HTTP response, encoded in base64."
Always base64?

2021-05-27 09:04 UTC, InbarPerry commented on steps/http/request/manifest.yaml
> +    description: "Headers of the request."
example won't show in the UI because of dedicated UI, but I added anyway.
I don't want to explain in the description about the delimiter because its not relevant to UI

2021-05-30 09:31 UTC, hagaishapira commented on steps/http/request/main.go
> +		return status.New(codes.Internal, http.StatusText(code), "")
I think the message should have a format of the status number and status text.

2021-05-30 09:31 UTC, hagaishapira commented on steps/http/request/main.go
> +		return output, codeToStatus(res.StatusCode)
what if there is an error where the body has some additional details like many apis do, I expect to get that in the verbose part of the status.

2021-05-30 09:31 UTC, hagaishapira commented on steps/http/request/main.go
> +		return output, codeToStatus(res.StatusCode)
Do you return that instead in the body?

2021-05-30 10:20 UTC, InbarPerry commented on steps/http/request/main.go
> +		return output, codeToStatus(res.StatusCode)
I do return that in the body

2021-05-30 14:42 UTC, hagaishapira commented
@InbarPerry perhaps move it from draft to review state?

2021-05-30 16:33 UTC, hagaishapira approved these changes
LGTM

2021-05-31 06:04 UTC, merged

2021-06-02 13:21 UTC, oriser commented on steps/http/request/input.go
> +	if duration > maxDuration {
What about min timeout?

2021-06-02 13:21 UTC, oriser commented on steps/http/request/input.go
> +			header.Add(key, strings.TrimLeft(v, " "))
You should trim also right? (Need to check in RFC if `a , b` will result `[a,b]` or `[a ,b]`

2021-06-02 13:21 UTC, oriser commented on steps/http/request/main.go
> +package main
As we said, this step can be generated

2021-06-02 13:21 UTC, oriser commented on steps/http/request/main.go
> +		return output, codeToStatus(res.StatusCode, verboseBody)
You can export `codeToStatus` to the SDK as a generic `HTTPCodeToStatus`

2021-06-02 13:21 UTC, oriser commented on steps/http/request/main.go
> +func codeToStatus(code int, body string) status.Status {
I would do 
```go
if code / 100 == 2 {
    return status.OK
}
```
As any 20X response is OK, for others I would continue to the switch