[SP-6300] WIP but formatted to deal with output
stackpulse/steps pull request #97
Opened 2021-05-26 09:53 UTC by igorkheif

2021-05-26 14:52 UTC, hagaishapira commented
@igorkheif is this ready for CR?

2021-05-26 14:54 UTC, igorkheif commented
@hagaishapira not yet

2021-05-30 07:56 UTC, hagaishapira requested changes
Overall looks much better, see comments and please also delete the duplicate steps with the specific cloud providers in this PR

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +func ParseArgs() (SSHParallelArgs, step.Status) {
I don't think you need this function, you can just call env.Parse from Init() and then do the validation if status isn't Failed()

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/command/manifest.yaml
> +    example: "77/zQpdlq3oUoB2P66Lu/3ZxgE3JoQA5vqPtV7dA"
Please fix output - if it's string then it should be just a string and not a json

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/base/ssh.go
> +		return status.New(codes.InvalidArgument, "gcp project is required when specifyng gcp secret", "")
please be consistent about case when writing GCP and AWS, you can always use upper case but search for all instances in the code and align

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/base/ssh.go
>  	err := envconf.Parse(&result)
don't use envconf directly use out wrapped env.Parse()

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/base/ssh.go
>  	envconf "github.com/caarlos0/env/v6"
don't need this

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +type SSHResponse struct {
rename this to SSHOutput and please make sure to have json tags which use snake case

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +	Error    string
```suggestion
	Hostname string `json:"hostname"`
	Success  bool `json:"success"`
	Output   string `json:"output"`
	Error    string `json:"error"`
```

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/manifest.yaml
> +  - name: output
do we know if this step is being used anywhere as we are having non-BC changes

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/manifest.yaml
>      example: "[{\"Hostname\":\"192.168.125.110\",\"Success\":true,\"Output\":\"ssh-command\\n\",\"Error\":\"\"},{\"Hostname\":\"192.168.125.112\",\"Success\":true,\"Output\":\"ssh-command\\n\",\"Erro
adjust output to new struct member names

2021-05-30 07:56 UTC, hagaishapira commented on steps/ssh/parallel-command/manifest.yaml
> +    type: "string"
please add in the description that if a command fails on any host the step will return success status with the error listed under the failed host in the output.

2021-05-30 09:02 UTC, oriser requested changes
See comments

2021-05-30 09:02 UTC, oriser commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +	err := envconf.Parse(&result)
The same here with the env

2021-05-30 13:46 UTC, igorkheif commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +func ParseArgs() (SSHParallelArgs, step.Status) {
👍

2021-05-30 13:47 UTC, igorkheif commented on steps/ssh/command/manifest.yaml
> +    example: "77/zQpdlq3oUoB2P66Lu/3ZxgE3JoQA5vqPtV7dA"
👍

2021-05-30 13:47 UTC, igorkheif commented on steps/ssh/base/ssh.go
>  	envconf "github.com/caarlos0/env/v6"
👍

2021-05-30 13:47 UTC, igorkheif commented on steps/ssh/base/ssh.go
>  	err := envconf.Parse(&result)
👍

2021-05-30 13:47 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +		return status.New(codes.InvalidArgument, "gcp project is required when specifyng gcp secret", "")
👍

2021-05-30 13:48 UTC, igorkheif commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +type SSHResponse struct {
`SSHOutput` is the new one, left `SSHResponse` as the BC one

2021-05-30 13:48 UTC, igorkheif commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +	Error    string
👍

2021-05-30 13:48 UTC, igorkheif commented on steps/ssh/parallel-command/manifest.yaml
> +  - name: output
👍

2021-05-30 13:48 UTC, igorkheif commented on steps/ssh/parallel-command/manifest.yaml
>      example: "[{\"Hostname\":\"192.168.125.110\",\"Success\":true,\"Output\":\"ssh-command\\n\",\"Error\":\"\"},{\"Hostname\":\"192.168.125.112\",\"Success\":true,\"Output\":\"ssh-command\\n\",\"Erro
👍

2021-05-30 13:49 UTC, igorkheif commented on steps/ssh/parallel-command/manifest.yaml
> +    type: "string"
👍

2021-05-30 13:50 UTC, igorkheif commented on steps/ssh/base/ssh.go
👍

2021-05-30 13:50 UTC, igorkheif commented on steps/ssh/base/ssh.go
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +	GCPAuthCode           string        `env:"AUTH_CODE" envDefault:""`
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +	GCPAuthCode           string        `env:"AUTH_CODE" envDefault:""`
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
>  	envconf "github.com/caarlos0/env/v6"
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
>  	}
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +		return "", nil, step.Status{
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +		return "", nil, step.Status{
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/command/ssh_command.go
> +	}, st
👍

2021-05-30 13:52 UTC, igorkheif commented on steps/ssh/parallel-command/ssh_parallel_command.go
> +	err := envconf.Parse(&result)
👍

2021-05-30 14:14 UTC, igorkheif commented on steps/ssh/base/ssh.go
> +func ValidateArgs(args SSHArgs) step.Status {
👍

2021-05-30 14:14 UTC, igorkheif commented on steps/ssh/parallel-command/manifest.yaml
> +  - name: output
Now returning new style and old style for BC as previously discussed

2021-05-30 14:18 UTC, igorkheif commented on steps/ssh/command/ssh_command.go
> +	}, st
This has always been "output". The one over at "ssh/parallel-command" is fixed.

2021-05-30 14:26 UTC, hagaishapira approved these changes
Really nice work! Have @oriser take a look and merge away

2021-05-30 14:33 UTC, igorkheif commented on steps/ssh/base/ssh.go
>  	err := envconf.Parse(&result)
👍

2021-05-30 15:04 UTC, oriser approved these changes
Looks great

2021-05-30 18:35 UTC, merged