[SP-6322] VictorOps updating to new conventions
stackpulse/steps pull request #99
Opened 2021-05-26 14:47 UTC by igorkheif

2021-05-31 11:45 UTC, hagaishapira requested changes

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/get-oncall/victorops_get_oncall_schedule.go
> +	st := base.GetStatus(resp.StatusCode)
Are you sure checking the status here isn't too late?
If you didn't get a success response won't it fail on the unmarshalling before we actually see this is a non successful response?

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/get-user-data/manifest.yaml
> +    description: "User's username"
all descriptions should have dots at the end of the sentences.

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/incident/acknowledge/victorops_incident_acknowledge.go
> +		return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
@oriser are we sure we want the same generic message for all these failure cases?

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/incident/acknowledge/victorops_incident_acknowledge.go
> +	st := base.GetStatus(resp.StatusCode)
Again with the place of when to check the status

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/incident/create-note/manifest.yaml
> +  - name: success
This is actually not needed as we have the step status which if it is success then the note should be created

2021-05-31 11:45 UTC, hagaishapira commented on steps/victorops/incident/create-note/victorops_incident_create_note.go
> +		return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
same question about the generic message

2021-05-31 12:08 UTC, igorkheif commented on steps/victorops/base/base.go
> +			Code:    codes.InvalidArgument,
In Victorops lingo 401 is "Authentication parameters missing". I can see it as either. Up to you.

2021-05-31 12:09 UTC, igorkheif commented on steps/victorops/base/base.go
> +		retStatus = status.Status{
This is "Authentication failed or rate-limit reached"

2021-05-31 12:10 UTC, igorkheif commented on steps/victorops/get-oncall/victorops_get_oncall_schedule.go
> +	st := base.GetStatus(resp.StatusCode)
Let's f2f about this

2021-05-31 13:19 UTC, oriser reviewed
See comments

2021-05-31 13:19 UTC, oriser commented on steps/victorops/base/base.go
> +			Code:    codes.InvalidArgument,
sounds legit

2021-05-31 13:19 UTC, oriser commented on steps/victorops/base/go.mod
>  go 1.14
```suggestion
go 1.16
```

2021-05-31 13:19 UTC, oriser commented on steps/victorops/get-oncall/victorops_get_oncall_schedule_test.go
> +			},
Why not using the matcher interfaces?
It's very hard to read it that way

2021-05-31 13:19 UTC, oriser commented on steps/victorops/get-user-data/victorops_get_user_data.go
> +	victoropsClient := victorops.NewClient(v.args.ApiID, v.args.ApiKey, "https://api.victorops.com")
Why are you using the VO library here but in the on call step you are using HTTP request?

2021-05-31 13:19 UTC, oriser commented on steps/victorops/get-user-data/victorops_get_user_data.go
> +		"ExpirationHours":     user.ExpirationHours,
Did we check if someone using this step? If no one is using, we can break it.
If you don't sure how to check DM me and let's do it together

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/acknowledge/victorops_incident_acknowledge.go
> +		return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
@igorkheif why did you decided to return a generic message here?

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/acknowledge/victorops_incident_acknowledge.go
> +		return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
Here for example, I think the most useful status is to write in the message the error returned from the unmarshaling and in the verbose, display the original respones (`fmt.Sprintf("original response: %s", string(rawRespBody))`)

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/create-note/victorops_incident_create_note.go
> +		return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
Same here

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/get/victorops_get_incident.go
> +			return nil, status.FromError(codes.Internal, base.GenericFailMessage, err)
same

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/create-note/victorops_incident_create_note_test.go
> +	resp, err := client.Do(req)
You can export it to the base

2021-05-31 13:19 UTC, oriser commented on steps/victorops/incident/get/victorops_get_incident.go
> +	victoropsClient := victorops.NewClient(s.ApiID, s.ApiKey, "https://api.victorops.com")
You can create the VO client in the base

2021-06-02 06:00 UTC, igorkheif commented on steps/victorops/base/base.go
> +
👍

2021-06-02 06:00 UTC, igorkheif commented on steps/victorops/base/go.mod
>  go 1.14
👍

2021-06-02 06:10 UTC, igorkheif commented on steps/victorops/get-user-data/manifest.yaml
> +    description: "User's username"
👍

2021-06-09 20:56 UTC, closed without merging